server:
  port: 8031

spring:
  application:
    name: servers-tea-stu
  datasource:
    url: jdbc:mysql://localhost:3306/mymanage?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    redis:
      port: 6379
      host: 192.168.91.128
      database: 0
      timeout: 1800000
jwt:
  expire: 604800000
  secret: myAuthenticaitonTest_#

#mybatis:
#  mapper-locations: classpath:com/test/serverslogin/mapper/xml/*.xml
mybatis-plus:
  mapper-locations: classpath:com/test/serverslogin/mapper/xml/*.xml
#  type-aliases-package: org/test/hospitalserver/utils