server:
  port: 6060

spring:
  application:
    name: HospitalServerApplication
  datasource:
    url: jdbc:mysql://localhost:3306/hospital
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 192.168.91.128
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


mybatis-plus:
  mapper-locations: org/test/hospitalserver/mapper/xml/*.xml
  type-aliases-package: org/test/hospitalserver/entity,org/test/hospitalutils/entity
  

