


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

server:
  port: 7070
# \u5E94\u7528\u540D\u79F0
mybatis:
  mapper-locations:  org.test.demo.mapper
  type-aliases-package: org.test.demo.utils