# 应用名称
spring:
  application:
    name: hospital-servers
  profiles:
    active: dev
    
swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}

